# Generated by Django 6.0.4 on 2026-07-15 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiscinaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Es. 'Listino Estate 2026'", max_length=100)),
                ('prezzo_ingresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_ombrellone', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_gazebo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_lettino', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_sdraia', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totale_ombrelloni', models.PositiveSmallIntegerField(default=0)),
                ('totale_gazebi', models.PositiveSmallIntegerField(default=0)),
                ('totale_lettini', models.PositiveSmallIntegerField(default=0)),
                ('totale_sdraie', models.PositiveSmallIntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inventario Piscina',
                'verbose_name_plural': 'Inventari Piscina',
            },
        ),
    ]
