# Generated by Django 6.0.4 on 2026-07-24 12:22

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiscinaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Es. 'Listino Estate 2026'", max_length=100)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('prezzo_ingresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_ombrellone', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_gazebo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_lettino', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_sdraia', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totale_ombrelloni', models.PositiveSmallIntegerField(default=0)),
                ('totale_gazebi', models.PositiveSmallIntegerField(default=0)),
                ('totale_lettini', models.PositiveSmallIntegerField(default=0)),
                ('totale_sdraie', models.PositiveSmallIntegerField(default=0)),
                ('orario_apertura', models.TimeField(default=datetime.time(10, 0), verbose_name='Orario di Apertura')),
                ('orario_chiusura', models.TimeField(default=datetime.time(19, 0), verbose_name='Orario di Chiusura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inventario Piscina',
                'verbose_name_plural': 'Inventari Piscina',
            },
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('OMBRELLONE', 'Ombrellone'), ('GAZEBO', 'Gazebo')], max_length=20)),
                ('numero', models.PositiveIntegerField(help_text='Numero identificativo della postazione')),
                ('pos_x', models.FloatField(default=50.0, help_text='Posizione orizzontale in percentuale (0-100) sul canvas')),
                ('pos_y', models.FloatField(default=50.0, help_text='Posizione verticale in percentuale (0-100) sul canvas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postazioni', to='struttura.piscinainventario')),
            ],
            options={
                'verbose_name': 'Postazione',
                'verbose_name_plural': 'Postazioni',
                'ordering': ['numero'],
                'unique_together': {('inventario', 'numero')},
            },
        ),
    ]
