# Generated by Django 6.0.4 on 2026-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postazione',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postazione',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='postazione',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('inventario', 'numero'), name='postazione_numero_unico_tra_le_attive'),
        ),
    ]
