# Generated by Django 6.0.4 on 2026-07-27 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0002_alter_postazione_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinainventario',
            name='eta_massima_bambino',
            field=models.PositiveSmallIntegerField(default=12, help_text='Età massima (inclusa) indicativamente ammessa alla tariffa bambini.', verbose_name='Età Massima Bambino'),
        ),
        migrations.AddField(
            model_name='piscinainventario',
            name='orario_inizio_ridotto',
            field=models.TimeField(default=datetime.time(14, 0), help_text="Da questo orario in poi l'ingresso ridotto pomeridiano è normalmente proposto.", verbose_name='Orario Inizio Ridotto Pomeridiano'),
        ),
        migrations.AddField(
            model_name='piscinainventario',
            name='prezzo_ingresso_bambino',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Prezzo Ingresso Bambini'),
        ),
        migrations.AddField(
            model_name='piscinainventario',
            name='prezzo_ingresso_ridotto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Prezzo Ingresso Ridotto Pomeridiano'),
        ),
    ]
