# Generated by Django 6.0.4 on 2026-07-15 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0002_piscinainventario_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinainventario',
            name='orario_apertura',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Orario di Apertura'),
        ),
        migrations.AddField(
            model_name='piscinainventario',
            name='orario_chiusura',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Orario di Chiusura'),
        ),
    ]
