# Generated by Django 6.0.4 on 2026-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0003_piscinainventario_orario_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinainventario',
            name='descrizione',
            field=models.TextField(blank=True, default=''),
        ),
    ]
