# Generated by Django 6.0.4 on 2026-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0003_piscinainventario_eta_massima_bambino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinainventario',
            name='eta_minima_bambino',
            field=models.PositiveSmallIntegerField(default=3, help_text="Sotto questa età l'ingresso è indicativamente gratuito.", verbose_name='Età Minima Bambino'),
        ),
    ]
