# Generated by Django 6.0.4 on 2026-07-18 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0004_piscinainventario_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('OMBRELLONE', 'Ombrellone'), ('GAZEBO', 'Gazebo')], max_length=20)),
                ('numero', models.PositiveIntegerField(help_text='Numero identificativo della postazione')),
                ('pos_x', models.FloatField(default=50.0, help_text='Posizione orizzontale in percentuale (0-100) sul canvas')),
                ('pos_y', models.FloatField(default=50.0, help_text='Posizione verticale in percentuale (0-100) sul canvas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postazioni', to='struttura.piscinainventario')),
            ],
            options={
                'verbose_name': 'Postazione',
                'verbose_name_plural': 'Postazioni',
                'ordering': ['numero'],
                'unique_together': {('inventario', 'numero')},
            },
        ),
    ]
