# Generated by Django 6.0.4 on 2026-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0004_piscinainventario_eta_minima_bambino'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazione',
            name='gruppo',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
