# Generated by Django 6.0.4 on 2026-09-04 10:46

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0005_postazione_gruppo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazionePadel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attivo', models.BooleanField(default=False, help_text='Se disattivato, il padel non è prenotabile online (lo staff può comunque registrare una partita).', verbose_name='Servizio padel attivo')),
                ('orario_apertura', models.TimeField(default=datetime.time(9, 0), verbose_name='Orario di Apertura')),
                ('orario_chiusura', models.TimeField(default=datetime.time(22, 0), verbose_name='Orario di Chiusura')),
                ('durata_partita_minuti', models.PositiveSmallIntegerField(default=90, verbose_name='Durata di una partita (minuti)')),
                ('prezzo_partita', models.DecimalField(decimal_places=2, default=0.0, help_text='Prezzo fisso per la prenotazione del campo, indipendente dal numero di partecipanti.', max_digits=6, verbose_name='Costo di una partita')),
                ('max_partecipanti', models.PositiveSmallIntegerField(default=4, verbose_name='Numero massimo di partecipanti')),
                ('prezzo_noleggio_palline', models.DecimalField(decimal_places=2, default=0.0, help_text='Prezzo per il set di palline, addebitato una sola volta per prenotazione.', max_digits=6, verbose_name='Costo noleggio palline')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Padel',
                'verbose_name_plural': 'Configurazione Padel',
            },
        ),
        migrations.CreateModel(
            name='GiornoChiusoPadel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Giorno Chiuso Padel',
                'verbose_name_plural': 'Giorni Chiusi Padel',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='RacchettaPadel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Marca ed eventuale modello, es. 'Babolat Air Viper'.", max_length=120, unique=True)),
                ('prezzo_noleggio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantita_disponibile', models.PositiveSmallIntegerField(default=1, help_text='Quante racchette di questo tipo possiede la struttura.', verbose_name='Pezzi disponibili')),
                ('disponibile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Racchetta Padel',
                'verbose_name_plural': 'Racchette Padel',
                'ordering': ['nome'],
            },
        ),
    ]
