# Generated by Django 6.0.4 on 2026-08-18 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponibile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VoceOrdine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantita', models.PositiveSmallIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note aggiuntive')),
            ],
            options={
                'verbose_name': 'Voce Ordine',
                'verbose_name_plural': 'Voci Ordine',
            },
        ),
    ]
