# Generated by Django 6.0.4 on 2026-08-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('prenotazioni', '0009_prenotazioneasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voceordine',
            name='prenotazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='prenotazioni.prenotazioneasporto'),
        ),
        migrations.AddField(
            model_name='voceordine',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voci_ordine', to='menu.prodotto'),
        ),
    ]
