# Generated by Django 6.0.4 on 2026-08-18 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allergene',
                'verbose_name_plural': 'Allergeni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Menu',
                'verbose_name_plural': 'Categorie Menu',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['categoria__nome', 'nome'], 'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AddField(
            model_name='prodotto',
            name='allergeni',
            field=models.ManyToManyField(blank=True, related_name='prodotti', to='menu.allergene'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='menu.categoria'),
        ),
    ]
