# Generated by Django 6.0.4 on 2026-08-18 13:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_allergene_categoria_alter_prodotto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneAsporto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orario_apertura', models.TimeField(default=datetime.time(11, 0), verbose_name='Orario di inizio disponibilità')),
                ('orario_chiusura', models.TimeField(default=datetime.time(22, 0), verbose_name='Orario di fine disponibilità')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Asporto',
            },
        ),
    ]
