# Generated by Django 6.0.4 on 2026-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_configurazioneasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti'),
        ),
    ]
