# Generated by Django 6.0.4 on 2026-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_prodotto_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergene',
            name='icona',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
