# Generated by Django 6.0.4 on 2026-08-19 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_seed_categoria_pizze'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornoChiusoAsporto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Giorno Chiuso Asporto',
                'verbose_name_plural': 'Giorni Chiusi Asporto',
                'ordering': ['data'],
            },
        ),
    ]
