# Generated by Django 6.0.4 on 2026-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_giornochiusoasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneasporto',
            name='limite_prodotti_orario',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Limite massimo di prodotti per orario'),
        ),
    ]
