# Generated by Django 6.0.4 on 2026-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_seed_categorie_bevande_vini'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneasporto',
            name='orario_apertura_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di inizio disponibilità (secondo turno)'),
        ),
        migrations.AddField(
            model_name='configurazioneasporto',
            name='orario_chiusura_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di fine disponibilità (secondo turno)'),
        ),
    ]
