# Generated by Django 6.0.4 on 2026-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_limite_prodotti_orario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneasporto',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='Prenotazioni online attive'),
        ),
    ]
