[pytest]
DJANGO_SETTINGS_MODULE = backend.settings
python_files = test_*.py
testpaths = users struttura prenotazioni menu
addopts = --cov=users --cov=struttura --cov=prenotazioni --cov=menu --cov-report=term-missing
