# Generated by Django 6.0.4 on 2026-09-16 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Expo push token')),
                ('piattaforma', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Staff',
                'verbose_name_plural': 'Dispositivi Staff',
                'ordering': ['-updated_at'],
            },
        ),
    ]
