# Generated by Django 6.0.4 on 2026-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cliente_created_at_cliente_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note aggiuntive'),
        ),
    ]
