# Generated by Django 6.0.4 on 2026-07-15 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('struttura', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazionePiscina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('stato', models.CharField(choices=[('PENDING', 'In Attesa'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Cancellata')], default='PENDING', max_length=20)),
                ('ingressi', models.PositiveSmallIntegerField(default=1)),
                ('ombrellone', models.PositiveSmallIntegerField(default=0)),
                ('gazebo', models.PositiveSmallIntegerField(default=0)),
                ('lettino', models.PositiveSmallIntegerField(default=0)),
                ('sdraia', models.PositiveSmallIntegerField(default=0)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prenotazioni', to='users.cliente')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='struttura.piscinainventario')),
            ],
            options={
                'verbose_name': 'Prenotazione Piscina',
                'verbose_name_plural': 'Prenotazioni Piscina',
            },
        ),
    ]
