# Generated by Django 6.0.4 on 2026-07-24 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazionePiscina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('stato', models.CharField(choices=[('PENDING', 'In Attesa'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Cancellata')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note aggiuntive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
                ('ingressi', models.PositiveSmallIntegerField(default=1)),
                ('ombrellone', models.PositiveSmallIntegerField(default=0)),
                ('gazebo', models.PositiveSmallIntegerField(default=0)),
                ('lettino', models.PositiveSmallIntegerField(default=0)),
                ('sdraia', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prenotazione Piscina',
                'verbose_name_plural': 'Prenotazioni Piscina',
            },
        ),
        migrations.CreateModel(
            name='OccupazionePostazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('numero_lettini', models.PositiveSmallIntegerField(default=0)),
                ('numero_sdraie', models.PositiveSmallIntegerField(default=0)),
                ('orario_arrivo_previsto', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupazioni', to='struttura.postazione')),
            ],
            options={
                'verbose_name': 'Occupazione Postazione',
                'verbose_name_plural': 'Occupazioni Postazione',
            },
        ),
    ]
