# Generated by Django 6.0.4 on 2026-07-15 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data di creazione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modifica'),
        ),
    ]
