# Generated by Django 6.0.4 on 2026-07-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prenotazioni', '0001_initial'),
        ('struttura', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prenotazioni', to='users.cliente'),
        ),
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='struttura.piscinainventario'),
        ),
        migrations.AddField(
            model_name='occupazionepostazione',
            name='prenotazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupazione_postazione', to='prenotazioni.prenotazionepiscina'),
        ),
        migrations.AlterUniqueTogether(
            name='occupazionepostazione',
            unique_together={('postazione', 'data')},
        ),
    ]
