# Generated by Django 6.0.4 on 2026-07-26 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_storico_da_postazioni_esistenti(apps, schema_editor):
    # Le postazioni già esistenti non hanno mai avuto uno storico: seminiamo una riga ancorata
    # alla loro data di creazione con la posizione ATTUALE (l'unica che conosciamo — non esiste
    # un vero storico pre-esistente da recuperare). Da qui in poi ogni nuovo spostamento crea/
    # aggiorna righe successive, quindi lo storico torna accurato in avanti.
    Postazione = apps.get_model('struttura', 'Postazione')
    PostazionePosizioneStorico = apps.get_model('prenotazioni', 'PostazionePosizioneStorico')
    for postazione in Postazione.objects.all():
        PostazionePosizioneStorico.objects.update_or_create(
            postazione=postazione,
            data=postazione.created_at.date(),
            defaults={'pos_x': postazione.pos_x, 'pos_y': postazione.pos_y},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_initial'),
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostazionePosizioneStorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico_posizioni', to='struttura.postazione')),
            ],
            options={
                'verbose_name': 'Storico Posizione Postazione',
                'verbose_name_plural': 'Storico Posizioni Postazione',
                'ordering': ['-data'],
                'unique_together': {('postazione', 'data')},
            },
        ),
        migrations.RunPython(seed_storico_da_postazioni_esistenti, migrations.RunPython.noop),
    ]
