# Generated by Django 6.0.4 on 2026-07-18 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_prenotazionepiscina_created_at_and_more'),
        ('struttura', '0005_postazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupazionePostazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('numero_lettini', models.PositiveSmallIntegerField(default=0)),
                ('numero_sdraie', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupazioni', to='struttura.postazione')),
                ('prenotazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupazione_postazione', to='prenotazioni.prenotazionepiscina')),
            ],
            options={
                'verbose_name': 'Occupazione Postazione',
                'verbose_name_plural': 'Occupazioni Postazione',
                'unique_together': {('postazione', 'data')},
            },
        ),
    ]
