# Generated by Django 6.0.4 on 2026-07-26 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_postazioneposizionestorico'),
        ('struttura', '0002_alter_postazione_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornoPienoPiscina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giorni_pieni', to='struttura.piscinainventario')),
            ],
            options={
                'verbose_name': 'Giorno Pieno Piscina',
                'verbose_name_plural': 'Giorni Pieni Piscina',
                'ordering': ['-data'],
                'unique_together': {('inventario', 'data')},
            },
        ),
    ]
