# Generated by Django 6.0.4 on 2026-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_occupazionepostazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupazionepostazione',
            name='orario_arrivo_previsto',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
