# Generated by Django 6.0.4 on 2026-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0004_giornopienopiscina'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='ingressi_bambini',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ingressi Bambini'),
        ),
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='ingressi_ridotti',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ingressi Ridotti Pomeridiani'),
        ),
    ]
