# Generated by Django 6.0.4 on 2026-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0005_prenotazionepiscina_ingressi_bambini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='ingressi_gratuiti',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ingressi Gratuiti'),
        ),
    ]
