# Generated by Django 6.0.4 on 2026-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0006_prenotazionepiscina_ingressi_gratuiti'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupazionepostazione',
            name='arrivato',
            field=models.BooleanField(default=False, verbose_name='Cliente arrivato'),
        ),
    ]
