# Generated by Django 6.0.4 on 2026-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0007_occupazionepostazione_arrivato'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionepiscina',
            name='creata_da_staff',
            field=models.BooleanField(default=False, verbose_name='Creata dallo staff'),
        ),
    ]
