# Generated by Django 6.0.4 on 2026-08-18 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0008_prenotazionepiscina_creata_da_staff'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneAsporto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('stato', models.CharField(choices=[('PENDING', 'In Attesa'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Cancellata')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note aggiuntive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
                ('creata_da_staff', models.BooleanField(default=False, verbose_name='Creato dallo staff')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prenotazioni', to='users.cliente')),
            ],
            options={
                'verbose_name': 'Prenotazione Asporto',
                'verbose_name_plural': 'Prenotazioni Asporto',
            },
        ),
    ]
