# Generated by Django 6.0.4 on 2026-09-04 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0009_prenotazioneasporto'),
        ('struttura', '0006_configurazionepadel_giornochiusopadel_racchettapadel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazionePadel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('stato', models.CharField(choices=[('PENDING', 'In Attesa'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Cancellata')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note aggiuntive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
                ('partecipanti', models.PositiveSmallIntegerField(default=4, verbose_name='Numero di partecipanti')),
                ('palline_noleggiate', models.BooleanField(default=False, verbose_name='Palline noleggiate')),
                ('durata_minuti', models.PositiveSmallIntegerField(default=90, verbose_name='Durata della partita (minuti)')),
                ('prezzo_partita', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prezzo_palline', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('creata_da_staff', models.BooleanField(default=False, verbose_name='Creata dallo staff')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prenotazioni', to='users.cliente')),
            ],
            options={
                'verbose_name': 'Prenotazione Padel',
                'verbose_name_plural': 'Prenotazioni Padel',
            },
        ),
        migrations.CreateModel(
            name='NoleggioRacchetta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantita', models.PositiveSmallIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('racchetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noleggi', to='struttura.racchettapadel')),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noleggi', to='prenotazioni.prenotazionepadel')),
            ],
            options={
                'verbose_name': 'Noleggio Racchetta',
                'verbose_name_plural': 'Noleggi Racchette',
                'ordering': ['racchetta__nome'],
                'unique_together': {('prenotazione', 'racchetta')},
            },
        ),
    ]
